#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 27 12:19:03 2022

@author: george
"""

import numpy as np
import pandas as pd
import glob, os
from matplotlib import pyplot as plt

%matplotlib qt 

file = '/Users/george/Desktop/from_Gabby/cropped_images_forlynaluotalk/GB_169_2022_03_15_HTEndothelial_BAPTA_plate3_GoF_15_MMStack_Default.ome_Cropped_locs_tracks.csv'

trackDF = pd.read_csv(file)















