#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 27 12:19:03 2022

@author: george
"""

import numpy as np
import pandas as pd
import glob, os
from matplotlib import pyplot as plt
import math

%matplotlib qt 

#raw
filePath = '/Users/george/Desktop/from_Gabby/binnedFiles/WT_fixed_rounded'

fileList = [f for f in glob.glob(filePath + "**/*_locs.csv", recursive=True)]


def roundup(x):
    '''round to nearest 100'''
    return int(math.ceil(x / 100.0)) * 100

for file in fileList:
    df = pd.read_csv(file)
    df['x [nm]'] = df['x [nm]'].apply(lambda x: roundup(x))
    df['y [nm]'] = df['y [nm]'].apply(lambda x: roundup(x))
    saveName = os.path.splitext(file)[0] + '_rounded.csv'
    df.to_csv(saveName)
    print(saveName + ' saved')















