#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  7 10:24:01 2018

@author: george
"""

from __future__ import print_function
import string
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import numpy as np

def char_to_pixels(text, path='arialbd.ttf', fontsize=14):
    """
    Based on https://stackoverflow.com/a/27753869/190597 (jsheperd)
    """
    font = ImageFont.truetype(path, fontsize) 
    w, h = font.getsize(text)  
    h *= 2
    image = Image.new('L', (w, h), 1)  
    draw = ImageDraw.Draw(image)
    draw.text((0, 0), text, font=font) 
    arr = np.asarray(image)
    arr = np.where(arr, 0, 1)
    arr = arr[(arr != 0).any(axis=1)]
    result = Image.fromarray((arr * 255).astype(np.uint8))
    savePath = '/Users/george/Desktop/text/'+'upper_'+text+'.png'
    result.save(savePath)
    return arr

def display(arr):
    result = np.where(arr, '#', ' ')
    print('\n'.join([''.join(row) for row in result]))

for c in string.ascii_uppercase:
    arr = char_to_pixels(
        c, 
        path='/Library/Fonts/Microsoft/Arial Bold.ttf', 
        fontsize=500)
    print(arr.shape)
    display(arr)
    print()